=== jllopezalvarez-profesor/DA1D1E-24-25-LLMM/UT05/Ejemplos/xsd/ejemplo-02.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="proyectos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="proyecto">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="direccion" type="employeeType" />
                            <xs:element name="coordinacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="empleado" type="employeeType" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="comunicacion" type="managerType" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="employeeType">
        <xs:sequence>
            <xs:element name="fistname" />
            <xs:element name="lastname" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="managerType">
        <xs:complexContent>
            <xs:extension base="employeeType">
                <xs:sequence>
                    <xs:element name="department" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== jllopezalvarez-profesor/DA1D1E-24-25-LLMM/UT05/Ejemplos/xsd/ejemplo-02.xml
<?xml version="1.0" encoding="UTF-8"?>
<proyectos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejemplo-02.xsd">
    <proyecto>
        <direccion>
            <fistname></fistname>
            <lastname></lastname>
        </direccion>
        <coordinacion>
            <empleado>
                <fistname></fistname>
                <lastname></lastname>
            </empleado>
        </coordinacion>
        <comunicacion>
            <fistname></fistname>
            <lastname></lastname>
        </comunicacion>

    </proyecto>
</proyectos>
