=== jllopezalvarez-profesor/DA1D1E-24-25-LLMM/examenes-resueltos/DTD-XSD-3EV/medicacion-paciente.dtd
<!ELEMENT pacientes (paciente+)>
<!ELEMENT paciente (datosPersonales,medicacion)>
<!ATTLIST paciente dni ID #REQUIRED>
<!ELEMENT datosPersonales (nombre,primer-apellido,segundo-apellido?,fecha-nacimiento,peso,altura,historial)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT primer-apellido (#PCDATA)>
<!ELEMENT segundo-apellido (#PCDATA)>
<!ELEMENT fecha-nacimiento (#PCDATA)>
<!ELEMENT peso (#PCDATA)>
<!ELEMENT altura (#PCDATA)>
<!ELEMENT historial (enfermedades?,alergias?)>
<!ELEMENT enfermedades (enfermedad*)>
<!ELEMENT enfermedad (#PCDATA)>
<!ELEMENT alergias (alergia*)>
<!ELEMENT alergia (#PCDATA)>
<!ELEMENT medicacion (medicamento*)>
<!ELEMENT medicamento (cantidad,frecuencia,duracionTratamiento?,indicaciones)>
<!ATTLIST medicamento nombre NMTOKEN #REQUIRED>
<!ATTLIST medicamento tipo (Comprimidos|CÃ¡psulas|Sobres|Inyectables) #IMPLIED>
<!ATTLIST medicamento dosis NMTOKEN #REQUIRED>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT frecuencia (#PCDATA)>
<!ELEMENT duracionTratamiento (#PCDATA)>
<!ELEMENT indicaciones (indicacion+)>
<!ELEMENT indicacion (#PCDATA)>

=== jllopezalvarez-profesor/DA1D1E-24-25-LLMM/examenes-resueltos/DTD-XSD-3EV/medicacion-paciente.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE pacientes SYSTEM "medicacion-paciente.dtd">
<pacientes>
    <paciente dni="D1234567X">
        <datosPersonales>
            <nombre>Juan</nombre>
            <primer-apellido>García</primer-apellido>
            <segundo-apellido>Martín</segundo-apellido>
            <fecha-nacimiento>1970-05-10</fecha-nacimiento>
            <peso>75</peso>
            <altura>175</altura>
            <historial>
                <enfermedades>
                    <enfermedad>Hipertensión</enfermedad>
                    <enfermedad>Diabetes tipo 2</enfermedad>
                </enfermedades>
                <alergias>
                    <alergia>Penicilina</alergia>
                </alergias>
            </historial>
        </datosPersonales>
        <medicacion>
            <medicamento nombre="Paracetamol" tipo="Comprimidos" dosis="650mg">
                <cantidad>1</cantidad>
                <frecuencia>Una vez al día, por la mañana con el desayuno</frecuencia>
                <duracionTratamiento>Indefinida</duracionTratamiento>
                <indicaciones>
                    <indicacion>Tomar con alimentos</indicacion>
                    <indicacion>Evitar el alcohol mientras se toma este medicamento</indicacion>
                </indicaciones>
            </medicamento>
            <medicamento nombre="Losartán" tipo="Cápsulas" dosis="50mg">
                <cantidad>2</cantidad>
                <frecuencia>Una vez al día, por la noche</frecuencia>
                <duracionTratamiento>Indefinida</duracionTratamiento>
                <indicaciones>
                    <indicacion>Tomar antes de dormir</indicacion>
                </indicaciones>
            </medicamento>
        </medicacion>
    </paciente>
</pacientes>
