<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
    <!ELEMENT agenda (contacto*)>
    <!ELEMENT contacto (nombre, (telefonoFijo, telefonoMovil?)+)>
    <!-- <!ELEMENT contacto (nombre, telefonoFijo, telefonoMovil?, telefonoFijo?)> -->
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT telefonoFijo (#PCDATA)>
    <!ELEMENT telefonoMovil (#PCDATA)>
]>
<!-- 
Dado el siguiente documento XML, añade el DTD necesario para que valide, teniendo en cuenta que
tendremos varios contactos en la agenda, pero que también puede estar vacía.
-->
<agenda>
    <contacto>
        <nombre>Ayuntamiento</nombre>
        <telefonoFijo>010</telefonoFijo>
    </contacto>
    <contacto>
        <nombre>Emergencias</nombre>
        <telefonoFijo>112 (Unión Europea)</telefonoFijo>
        <telefonoMovil>Desconocido</telefonoMovil>
        <telefonoFijo>911 (Estados Unidos)</telefonoFijo>
    </contacto>
</agenda>