<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE animales [
    <!ELEMENT animales (perro*, gato*)>
    <!ELEMENT perro (#PCDATA)>
    <!ELEMENT gato (#PCDATA)>
]>
<!-- 
Dado el siguiente documento XML, añade el DTD necesario para que valide. Teniendo en cuenta que
podemos tener más de una raza de perro y más de una de gato. O ninguna de perro o ninguna de gato. 
-->
<animales>
    <perro>Caniche</perro>
    <perro>Caniche</perro>
    <gato>Siamés</gato>
    <gato>Siamés</gato>
</animales>