<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jornada [
    <!ELEMENT jornada (equipos, partidos)>
    <!ELEMENT equipos (equipo+)>
    <!ELEMENT partidos (partido+)>
    <!ELEMENT equipo (nombre, entrenador, localidad, puesto, 
    partidosJugados, partidosPerdidos, partidosEmpatados, golaveraje)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT entrenador (#PCDATA)>
    <!ELEMENT localidad (#PCDATA)>
    <!ELEMENT puesto (#PCDATA)>
    <!ELEMENT partidosJugados (#PCDATA)>
    <!ELEMENT partidosPerdidos (#PCDATA)>
    <!ELEMENT partidosEmpatados (#PCDATA)>
    <!ELEMENT golaveraje (golesAFavor, golesEnContra)>
    <!ELEMENT golesAFavor (#PCDATA)>
    <!ELEMENT golesEnContra (#PCDATA)>
    <!ELEMENT partido (local, visitante, golesLocal, golesVisitante)>
    <!ELEMENT local (#PCDATA)>
    <!ELEMENT visitante (#PCDATA)>
    <!ELEMENT golesLocal (#PCDATA)>
    <!ELEMENT golesVisitante (#PCDATA)>
]>

<jornada>
    <equipos>
        <equipo>
            <nombre></nombre>
            <entrenador></entrenador>
            <localidad></localidad>
            <puesto></puesto>
            <partidosJugados></partidosJugados>
            <partidosPerdidos></partidosPerdidos>
            <partidosEmpatados></partidosEmpatados>
            <golaveraje>
                <golesAFavor></golesAFavor>
                <golesEnContra></golesEnContra>
            </golaveraje>
        </equipo>
    </equipos>
    <partidos>
        <partido>
            <local></local>
            <visitante></visitante>
            <golesLocal></golesLocal>
            <golesVisitante></golesVisitante>
        </partido>
    </partidos>
</jornada>

<!-- 
Se quiere definir un lenguaje de marcas para representar los resultados de una jornada de una liga
de fútbol. La información que se quiere almacenar de cada partido es:
    • Nombre del equipo local.
    • Nombre del equipo visitante.
    • Goles marcados por el equipo local.
    • Goles marcados por el equipo visitante
    • Los resultados de los partidos son los siguientes:
        ◦ Alpedrete: 0 - Madracos: 1
        ◦ Guadarrama: 3 - Villalba: 3
        ◦ CD El Escorial: 4 – Torrelodones: 2

Además, el XML tendrá, además de los resultados, la información de los equipos participantes en la
liga. Por cada equipo:
    • Nombre del equipo
    • Nombre del entrenador
    • Localidad
    • Posición en la liga
    • Partidos (número de partidos)
        ◦ Partidos jugados 
        ◦ Partidos perdidos
        ◦ Partidos empatados
    • Golaveraje (número de goles)
        ◦ Goles a favor
        ◦ Goles en contra

-->