<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cine [
    <!ELEMENT cine (peliculas, actores)>
    <!ELEMENT peliculas (pelicula)*>
    <!ELEMENT pelicula (#PCDATA)>
    <!ATTLIST pelicula codpel ID (P1 | P2 | P3 | P4) "P0">
    <!ELEMENT actores (actor)*>
    <!ELEMENT actor (#PCDATA)>
    <!ATTLIST actor filmografia IDREFS #REQUIRED>
]>
<!-- Dado el siguiente XML, modifícalo para que sea válido, SIN MODIFICAR la DTD -->
<!-- Cuando el atributo es ID no deja que se use la notación OR (|) -->
<!-- Este ejercicio no se puede resolver sin cambiar el DTD -->
<cine>
    <peliculas>
        <pelicula>Avatar</pelicula>
        <pelicula codpel="P1">Gran Torino</pelicula>
        <pelicula codpel="P2">Invictus</pelicula>
        <pelicula codpel="P3">Million dollar baby</pelicula>
        <pelicula codpel="P4">Oblivion</pelicula>
        <pelicula codpel="P5">Unforgiven</pelicula>
    </peliculas>
    <actores>
        <actor filmografia="P1 P3 P5">Clint Eastwood</actor>
        <actor filmografia="P2 P3 P4 P5">Morgan Freeman</actor>
        <actor filmografia="P4">Tom Cruise</actor>
    </actores>
</cine>