<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE geografiaMundial [
    <!ELEMENT geografiaMundial (pais+)>
    <!ELEMENT pais (nombre, continente, capital)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT continente (#PCDATA)>
    <!ELEMENT capital (#PCDATA)>
]>
<!-- 
Dado el siguiente documento XML, añade el DTD necesario para que valide. Ten en cuenta que al menos
tendremos un país, y que todos los elementos del país son obligatorios. 
-->
<!-- El enunciado era incorrecto, no se puede resolver sin cambiar uno de los elementos "pais"-->
<!-- Decidimos cambiar el "pais" interior por "nombre" -->
<geografiaMundial>
    <pais>
        <nombre>España</nombre>
        <continente>Europa</continente>
        <capital>Madrid</capital>
    </pais>
</geografiaMundial>