<?xml version="1.0" encoding="UTF-8"?>
<!-- Dado el siguiente documento XML, aÃ±ade el DTD necesario para que valide. -->
<!DOCTYPE root [
    <!ELEMENT root (records)>
    <!ELEMENT records (record*)>
    <!ELEMENT record (title?, artist, genre, year)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT artist (#PCDATA)>
    <!ELEMENT genre (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
]>
<root>
    <records>
        <record>
            <title>Brand New Eyes</title>
            <artist>Paramore</artist>
            <genre>Punk Rock</genre>
            <year>2011</year>
        </record>
        <record>
            <artist>Various Artist</artist>
            <genre>Rock</genre>
            <year />
        </record>
    </records>
</root>